import Link from 'next/link';
import getAllUsers from '@/lib/getAllUsers';
import { User } from '../../types/user';
import { FC } from 'react';

export const metadata = {
  title: 'Users Page',
  description: 'Generated by create next app',
};

const UserPage: FC = async () => {
  const usersData: Promise<User[]> = getAllUsers();
  const users = await usersData;

  //   if (usersData) {
  //        in VSCODE TERMINAL
  //     console.log(usersData);
  //   }

  return (
    <section style={{ padding: '50px' }}>
      <h1 style={{ marginBottom: '50px', color: 'red' }}>
        <Link href="/">Back to Home</Link>
      </h1>
      <br />
      {users.map(({ ...user }: User) => (
        <>
          <p key={user.id}>
            <Link href={`/users/${user.id}`}>{user.name}</Link>
          </p>
          <br />
        </>
      ))}
    </section>
  );
};

export default UserPage;
