import getUserById from '@/lib/getUserById';
import { User } from '@/types/user';
import { Metadata } from 'next';
import { Params } from 'next/dist/shared/lib/router/utils/route-matcher';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

//or create heat.tsx file
// export const metadata = {
//   title: 'Page',
//   description: 'Generated by create next app',
// };

//fn for Metadata not work in 'use client';
export async function generateMetadata({ params: { id } }: Params): Promise<Metadata> {
  const userData: Promise<User> = getUserById(id);
  const user: User = await userData;

  return {
    title: user.name,
    description: `This is the page of ${user.name}`,
  };
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      {/* <head /> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
